import paramiko,time
con=paramiko.SSHClient()
con.set_missing_host_key_policy(paramiko.AutoAddPolicy())
con.connect('192.168.1.1',username='cisco',password='cisco',look_for_keys=False,allow_agent=False)
new_con=con.invoke_shell()
output=new_con.recv(5000)
print(output)
new_con.send('sh ver')
time.sleep(3)
output=new_con.recv(5000)
print(output)
new_con.close()
